### ISSUE TITLE
No video/black screen

### ISSUE THREAD

**Issue by tERB00** [geekman/t20-rtspd#3]
My hardware is Xiaofang 1S T20L 64MB jxf23 sensor
I'm running latest version of Xiaomi-Dafang-Hacks firmware.
I've stopped rtsp-h264 service and started t20-rtspd binary. Here is what I get:
```
[root@XiaoFANG-1:~]# ./t20-rtspd
my-carrier-server version: Oct  1 2019_14:38:59_e17abca
>>>>>caputre_and_encoding start
i264e[info]: profile Main, level 4.0
[chn0] scaler->outwidth = 0 scaler->outheight = 0, sscaler.outwidth = 0 sscaler.outheight = 0

"stream" stream, from the file "/tmp/h264_fifo"
Play this stream using the URL "rtsp://10.10.10.118/stream"
```
I am able to connect to the stream but there is no video or audio - just black screen.

How can I troubleshoot it? Is there any logs or debug output or something?

**Comment by aminhusni** [comment]
Try disabling autostart on the original RTSP server then reboot the camera. Then login SSH and start the binary. 
I had this problem earlier but doing the above fixed it.

**Comment by tERB00** [comment]
> Try disabling autostart on the original RTSP server then reboot the camera. Then login SSH and start the binary.
> I had this problem earlier but doing the above fixed it.

Yeah, well... that solved the problem... kind of... It works now but the picture quality is horrible. 

Looks like very low bitrate settings. Is there any way to change it or they are hardcoded?

**Comment by aminhusni** [comment]
Seems like it is hardcoded. 
Refer to 
https://github.com/geekman/t20-rtspd/blob/56ab9def6b060ddd31e8531801ba62a3d4eaaf8d/imp-common.c#L503

**Comment by tERB00** [comment]
Only 2k? Yeah, that's really low... Also no sound. I'm not gonna use this streamer at that state...
