### ISSUE TITLE
Interest in working on OpenMiko?

### ISSUE THREAD

**Issue by tachang** [geekman/t20-rtspd#6]
Hi,
  I'm one of the creators of a project called OpenMiko. It is a bit of a combination between dafang hacks and openfang. Just thought I'd reach out if you're interested: https://github.com/openmiko/openmiko

Thanks,
Jeff

**Comment by geekman** [comment]
Thanks for the invitation, but I'm afraid I don't really have the capacity to work on it.

**Comment by tachang** [comment]
Sounds good!
