### ISSUE TITLE
Calling StartRecvPic every time frames are retrieves seems to confuse VBR

### ISSUE THREAD

**Issue by wryun** [geekman/t20-rtspd#8]
Other Ingenic encoders call StartRecvPic after setting up the encoding stream, and only call Stop when it finishes.

This server - presumably because it was based on the sample code which simply wrote a certain number of frames to the file - calls it every time before polling the stream. This seems to cause VBR to get quite confused (lower bitrate) and significantly reduces the image quality in this mode.

**Comment by wryun** [comment]
Oops - I think I did this to myself by uncommenting StopRecvPic a while ago while I was messing with something else, so this is probably not an issue, though I haven't bothered to confirm. I do think it would be nicer to call StartRecvPic only once.

**Comment by geekman** [comment]
Nice catch. It definitely looks like it should have only been called once during setup instead of every polling cycle.
